const {test}=require('node:test'),assert=require('node:assert/strict'),{runtime}=require('./source-runtime.cjs');
function setup(){const r=runtime();r.click('demolobby');r.click('start');assert.equal(r.app.engine.state.session.phase,'CAMPAIGN');return r}
function route(r,x,y){assert.ok(r.app.world.walkTo(x,y),'route missing '+x+','+y);let n=0;while(r.app.world.route.length&&n++<3000)r.app.world.tick(20,(type,args)=>r.app.engine.dispatch(type,args));assert.ok(n<3000,'route failed to finish');assert.ok(Math.hypot(r.app.engine.state.player.x-x,r.app.engine.state.player.y-y)<22,'route stopped early');}
function exterior(r,id){r.click('goto',{id});let n=0;while(r.app.world.route.length&&n++<3000)r.app.world.tick(20,(type,args)=>r.app.engine.dispatch(type,args));assert.ok(n<3000);r.click('interact');assert.equal(r.app.engine.state.player.inside,id);}
function command(r,type,args={}){r.click('command',{type,args});const msg=r.elements.toast.textContent;assert.ok(!r.logs.length,JSON.stringify(r.logs));return msg}
test('all UI source panels render without exceptions (DOM harness, not browser)',()=>{const r=setup();for(const page of ['map','economy','society','politics','laws','inventory','player','phone','contacts','messages','save','help']){r.app.open(page);assert.ok(r.elements.dialogBody.innerHTML.length>50);assert.ok(!r.elements.dialogBody.innerHTML.includes('undefined'))}assert.deepEqual(r.logs,[])});
test('controls reach physical congress, open hall door and walk to lectern',()=>{const r=setup();exterior(r,'congress');route(r,500,580);r.click('interact');assert.ok(r.app.engine.state.world.doors.congress['Acceso interior']);route(r,500,260);r.click('interact');assert.equal(r.app.panel,'building');assert.ok(r.elements.dialogTitle.textContent.includes('campaña'));r.app.close();route(r,500,680);r.click('interact');assert.equal(r.app.engine.state.player.inside,null);assert.deepEqual(r.logs,[])});
test('three-party campaign, ballot, elected actor law, economy and save via UI handlers',()=>{const r=setup();assert.equal(r.app.engine.state.politics.parties.length,3);exterior(r,'congress');route(r,520,655);r.click('interact');assert.equal(r.app.panel,'campaign');command(r,'CAMPAIGN');r.app.close();r.click('advance',{days:7});assert.equal(r.app.engine.state.session.phase,'BALLOT');route(r,790,680);r.click('interact');assert.equal(r.app.panel,'ballot');command(r,'BALLOT',{party:r.app.engine.state.player.party});r.click('advance',{days:2});assert.ok(r.app.engine.state.politics.president.id);r.app.close();const presidentId=r.app.engine.state.politics.president.id;r.handlers.change({target:{id:'actorSelect',value:presidentId}});assert.equal(r.app.engine.state.player.id,presidentId);if(!r.app.engine.state.player.inside)exterior(r,'congress');route(r,500,580);if(!r.app.engine.state.world.doors.congress['Acceso interior'])r.click('interact');route(r,500,260);r.click('interact');r.click('tab',{tab:'new'});r.elements.lawKey.value='tax';r.elements.lawValue.value='25';r.elements.billTitle.value='Reforma verificada';r.click('propose');assert.equal(r.app.engine.state.politics.bills.length,1);r.click('advance',{days:2});const bill=r.app.engine.state.politics.bills[0];assert.equal(bill.status,'EXECUTIVE');r.app.close();route(r,500,160);r.click('interact');assert.ok(r.elements.dialogBody.innerHTML.includes('Promulgar'));command(r,'EXECUTIVE',{id:bill.id});assert.equal(r.app.engine.state.policy.tax,.25);r.click('advance',{days:7});assert.notEqual(r.app.engine.state.society.approval,57);r.app.open('save');r.click('save');const saved=r.storage.get('argentum2d-save');assert.ok(saved);r.click('advance',{days:1});r.click('load');assert.equal(r.app.engine.save(),saved);assert.deepEqual(r.logs,[])});
test('market physical aisle cart cashier actions work through controls',()=>{const r=setup();exterior(r,'market');route(r,500,580);r.click('interact');route(r,155,250);r.click('interact');assert.equal(r.app.engine.state.player.cart.water,1);route(r,520,500);r.click('interact');assert.equal(r.app.panel,'building');command(r,'CHECKOUT');assert.equal(r.app.engine.state.player.inventory.water,4);assert.ok(r.app.engine.state.goals.purchase);assert.deepEqual(r.logs,[])});
test('football controls enter pitch, dribble, shoot and register a goal',()=>{const r=setup();exterior(r,'pitch');r.click('interact');assert.equal(r.app.panel,'football');r.click('footballstart',{mode:'practice'});assert.equal(r.app.engine.state.football.status,'PLAYING');r.handlers.keydown({key:'d',preventDefault(){}});for(let i=0;i<139;i++){r.app.world.tick(20,(t,a)=>r.app.engine.dispatch(t,a));r.app.engine.dispatch('PHYSICS',{dt:.02})}r.handlers.keyup({key:'d'});assert.ok(r.app.engine.state.player.x>970);assert.ok(r.app.engine.state.football.ball.x>r.app.engine.state.player.x);r.app.world.aim={x:1080,y:340};r.handlers.keydown({key:' ',preventDefault(){}});for(let i=0;i<20;i++)r.app.engine.dispatch('PHYSICS',{dt:.05});assert.equal(r.app.engine.state.football.score[0],1);assert.deepEqual(r.logs,[])});
test('weapon controls retrieve physical kit, equip, hit and record a cause',()=>{const r=setup();exterior(r,'police');route(r,500,580);r.click('interact');route(r,175,455);r.click('interact');assert.equal(r.app.panel,'inventory');assert.equal(r.app.engine.state.player.inventory.pistol,1);r.click('equip',{id:'pistol'});r.app.close();route(r,500,680);r.click('interact');assert.equal(r.app.engine.state.player.inside,null);route(r,830,810);r.app.world.clickAction({x:870,y:810});for(let i=0;i<5;i++)r.app.engine.dispatch('PHYSICS',{dt:.05});assert.equal(r.app.engine.state.world.actors.outside[0].health,72);assert.equal(r.app.engine.state.justice.cases[0].suspect,'player');assert.deepEqual(r.logs,[])});
