const assert=require('node:assert/strict'),{test}=require('node:test'),A=require('../src/engine.js'),G=require('../src/governance.js'),I=require('../src/interiors.js');
function cmd(e,type,args={}){const r=e.dispatch(type,args);assert.ok(r.ok,type+': '+r.error);return e.state}
function start(){const e=new A.Engine();cmd(e,'LOBBY_CREATE',{name:'Partido Uno'});cmd(e,'LOBBY_ADD',{name:'Juez Uno'});const party=e.state.politics.parties[0],other=Object.keys(e.state.players).find(id=>id!=='player');cmd(e,'LOBBY_ASSIGN',{party:party.id,slot:'president',player:'player'});cmd(e,'LOBBY_ASSIGN',{party:party.id,slot:'judge',player:other});cmd(e,'LOBBY_READY',{party:party.id});cmd(e,'LOBBY_BOTS');cmd(e,'START');return e}
function at(e,id,kind){const o=I.get(id).objects.find(x=>x.kind===kind);Object.assign(e.state.player,{inside:id,x:o.x+o.w/2,y:o.y+o.h+25});}
function elected(){const e=start();cmd(e,'ADVANCE',{days:9});e.switchActor(e.state.politics.president.id);return e}
function promised(){const e=start();e.state.politics.campaign[e.state.player.party]=45;at(e,'plaza','campaign');cmd(e,'PROMISE_CREATE',{key:'tax',value:.25});cmd(e,'ADVANCE',{days:9});assert.equal(e.state.politics.president.id,'player');assert.equal(e.state.governance.promises[0].status,'IN_PROGRESS');return e}
test('executive measures require elected actor, physical desk, treasury and delayed service; conserve money',()=>{
 const e=elected(),id=e.state.player.id;assert.equal(e.dispatch('GOVERNMENT_MEASURE',{id:'hospital_equipment'}).ok,false);at(e,'congress','executive');const before=e.state.accounts.treasury,quality=e.state.economy.healthQuality,total=Object.values(e.state.accounts).reduce((a,b)=>a+b,0);
 cmd(e,'GOVERNMENT_MEASURE',{id:'hospital_equipment'});assert.equal(e.state.accounts.treasury,before-18000);assert.equal(e.state.economy.healthQuality,quality);assert.equal(G.bonus(e.state,'healthQuality'),0);assert.equal(e.state.governance.budget.byArea.SALUD,18000);assert.ok(Math.abs(Object.values(e.state.accounts).reduce((a,b)=>a+b,0)-total)<.001);
 assert.equal(e.dispatch('GOVERNMENT_MEASURE',{id:'hospital_equipment'}).ok,false);cmd(e,'ADVANCE',{days:3});assert.equal(G.bonus(e.state,'healthQuality'),10);cmd(e,'ADVANCE',{days:30});assert.equal(G.bonus(e.state,'healthQuality'),0);assert.equal(e.state.governance.measures[0].status,'COMPLETED');
 const other=Object.keys(e.state.players).find(x=>x!==id);e.switchActor(other);at(e,'congress','executive');assert.equal(e.dispatch('GOVERNMENT_MEASURE',{id:'police_equipment'}).ok,false);
});
test('insufficient treasury rejects a measure atomically; old saves initialize governance safely',()=>{const e=elected();at(e,'congress','executive');e.state.accounts.population+=e.state.accounts.treasury-100;e.state.accounts.treasury=100;const saved=e.save();assert.equal(e.dispatch('GOVERNMENT_MEASURE',{id:'road_maintenance'}).ok,false);assert.equal(e.save(),saved);const old=JSON.parse(saved);delete old.state.governance;assert.ok(e.load(JSON.stringify(old)).ok);cmd(e,'ADVANCE',{days:1});assert.equal(e.state.governance.schema,1)});
test('promise links actual enacted law; campaign permissions and mismatched bill cannot forge fulfillment',()=>{const e=start();assert.equal(e.dispatch('PROMISE_CREATE',{key:'tax',value:.25}).ok,false);at(e,'plaza','campaign');assert.equal(e.dispatch('PROMISE_CREATE',{key:'tax',value:99}).ok,false);const p=promised();at(p,'congress','congress');cmd(p,'PROPOSE',{key:'tax',value:.25});const b=p.state.politics.bills[0],pr=p.state.governance.promises[0];at(p,'congress','executive');assert.equal(p.dispatch('PROMISE_LINK',{id:pr.id,billId:999}).ok,false);cmd(p,'PROMISE_LINK',{id:pr.id,billId:b.id});cmd(p,'ADVANCE',{days:2});assert.equal(p.state.governance.promises[0].status,'IN_PROGRESS');cmd(p,'EXECUTIVE',{id:b.id});assert.equal(p.state.governance.promises[0].status,'FULFILLED');assert.equal(p.state.governance.credibility[pr.party],2);cmd(p,'ADVANCE',{days:2});assert.equal(p.state.governance.credibility[pr.party],2)});
test('amendment preserves versions, clears old block support and votes amended tax used at checkout',()=>{const e=elected();at(e,'congress','congress');cmd(e,'PROPOSE',{key:'tax',value:.25});let b=e.state.politics.bills[0];cmd(e,'BLOCK_STANCE',{id:b.id,vote:'YES'});cmd(e,'AMEND',{id:b.id,value:.22});b=e.state.politics.bills[0];assert.equal(b.revision,2);assert.deepEqual(b.versions.map(v=>v.value),[.25,.22]);assert.deepEqual(b.blockStance,{});cmd(e,'ADVANCE',{days:2});at(e,'congress','executive');cmd(e,'EXECUTIVE',{id:b.id});assert.equal(e.state.policy.tax,.22);at(e,'market','shelf');const shelf=I.get('market').objects.find(o=>o.kind==='shelf');cmd(e,'CART_ADD',{id:shelf.id});at(e,'market','market');const treasury=e.state.accounts.treasury,total=A.price(e.state,shelf.product);cmd(e,'CHECKOUT');assert.ok(Math.abs((e.state.accounts.treasury-treasury)-Math.round(total/1.22*.22*100)/100)<.03)});
test('institutional block differs from abandonment and a later enacted override fulfills the promise',()=>{const e=promised();at(e,'congress','congress');cmd(e,'PROPOSE',{key:'tax',value:.25});const b=e.state.politics.bills[0],pr=e.state.governance.promises[0];at(e,'congress','executive');cmd(e,'PROMISE_LINK',{id:pr.id,billId:b.id});cmd(e,'ADVANCE',{days:2});cmd(e,'EXECUTIVE',{id:b.id,veto:true});assert.equal(e.state.governance.promises[0].status,'BLOCKED_EXECUTIVE');assert.equal(e.state.governance.credibility[pr.party],-.5);
 // Isolate institutional review: simulate the already validated override enactment outcome.
 e.state.politics.bills[0].status='ENACTED';e.state.policy.tax=.25;G.review(e.state,()=>{});assert.equal(e.state.governance.promises[0].status,'FULFILLED');assert.equal(e.state.governance.credibility[pr.party],2);
 const a=promised();at(a,'congress','executive');cmd(a,'PROMISE_ABANDON',{id:a.state.governance.promises[0].id});assert.equal(a.state.governance.credibility[a.state.player.party],-3);
});
