// Exercises source modules without a browser. This is not a browser-layout test.
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{createCanvas}=require('@napi-rs/canvas');
function runtime(width=1200,height=780,options={}){
const intervals=[],timers=[];
const elements={},handlers={},raf=[],logs=[];let currentDocument;
class El{constructor(id=''){this.id=id;this.style={};this.dataset={};this.value='';this.tagName='DIV';this.offsetParent={};this.classList={add(){},remove(){},toggle(){}};this.events={};this.children=[];this._html='';this.textContent='';this.clientWidth=width;this.clientHeight=height;}
set innerHTML(v){this._html=v;for(const m of v.matchAll(/<(input|select)[^>]*id="([^"]+)"[^>]*>/g)){const el=currentDocument.getElementById(m[2]);el.tagName=m[1].toUpperCase();el.value=m[0].match(/value="([^"]*)"/)?.[1]||'';} }
get innerHTML(){return this._html}addEventListener(k,fn){this.events[k]=fn}focus(){currentDocument.activeElement=this}querySelector(){return new El()}querySelectorAll(){return[]}getBoundingClientRect(){return{x:0,y:0,left:0,top:0,width,height}}closest(){return this}click(){handlers.click?.({target:this})}}
const document={activeElement:new El(),getElementById(id){return elements[id]||(elements[id]=new El(id))},createElement(tag){if(tag==='canvas')return createCanvas(1550,1200);return new El()},addEventListener(k,fn){const old=handlers[k];handlers[k]=old?e=>{old(e);fn(e)}:fn},querySelectorAll(){return[]}};document.body=new El('body');document.body.appendChild=el=>{elements[el.id]=el};currentDocument=document;const canvas=createCanvas(width,height);canvas.clientWidth=width;canvas.clientHeight=height;canvas.events={};canvas.addEventListener=(k,fn)=>canvas.events[k]=fn;canvas.getBoundingClientRect=()=>({left:0,top:0});elements.city=canvas;
const storage=new Map(),sandbox={document,console:{log:(...a)=>logs.push(a.join(' ')),error:(...a)=>logs.push('ERROR '+a.join(' '))},devicePixelRatio:1,ResizeObserver:class{constructor(f){this.f=f}observe(){this.f()}},requestAnimationFrame:f=>raf.push(f),setTimeout:()=>1,clearTimeout(){},localStorage:{setItem:(k,v)=>storage.set(k,v),getItem:k=>storage.get(k)||null},Blob,URL,Date,Intl,performance:{now:()=>0},addEventListener(){}};if(options.online){Object.assign(sandbox,{WebSocket:options.WebSocket||require('ws'),location:new URL(options.url),setTimeout:(f,ms)=>{const id=setTimeout(f,ms);timers.push(id);return id},clearTimeout,setInterval:(f,ms)=>{const id=setInterval(f,ms);intervals.push(id);return id},clearInterval,sessionStorage:{setItem:(k,v)=>storage.set('session:'+k,v),getItem:k=>storage.get('session:'+k)||null,removeItem:k=>storage.delete('session:'+k)},navigator:{mediaDevices:options.mediaDevices}})}sandbox.window=sandbox;sandbox.globalThis=sandbox;vm.createContext(sandbox);
for(const file of ['data','interiors','lobby','physical','governance','engine','world',...(options.online?['network','voice']:[]),'ui'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../src',file+'.js'),'utf8'),sandbox,{filename:file+'.js'});
function click(action,args={}){const el=new El();el.dataset={action,args:JSON.stringify(args)};handlers.click({target:el});}
function frame(t){const fn=raf.shift();if(fn)fn(t)}
return{ctx:sandbox,app:sandbox.ARGENTUM_APP,elements,handlers,click,frame,canvas,logs,storage,cleanup(){sandbox.ARGENTUM_APP.engine.leave?.();intervals.forEach(clearInterval);timers.forEach(clearTimeout)}};}
module.exports={runtime};
if(require.main===module){const r=runtime();console.log('boot',r.app.panel,r.elements.dialogTitle.textContent);r.click('demolobby');r.click('start');console.log('started',r.app.engine.state.session.phase,r.logs);for(const page of ['map','economy','society','politics','laws','inventory','player','phone','contacts','messages','save','help']){r.app.open(page);console.log(page,r.elements.dialogTitle.textContent,r.elements.dialogBody.innerHTML.length)}r.app.close();r.frame(16);console.log('errors',r.logs.filter(l=>l.startsWith('ERROR')));}
