const assert=require('node:assert/strict'),{test}=require('node:test'),A=require('../src/engine.js'),D=require('../src/data.js'),I=require('../src/interiors.js');
function cmd(e,type,args={}){const r=e.dispatch(type,args);assert.ok(r.ok,type+': '+r.error);return e.state}
function setup(){const e=new A.Engine();cmd(e,'LOBBY_CREATE',{name:'Partido Uno'});cmd(e,'LOBBY_ADD',{name:'Juez Uno'});const party=e.state.politics.parties[0],other=Object.keys(e.state.players).find(id=>id!=='player');cmd(e,'LOBBY_ASSIGN',{party:party.id,slot:'president',player:'player'});cmd(e,'LOBBY_ASSIGN',{party:party.id,slot:'judge',player:other});cmd(e,'LOBBY_READY',{party:party.id});cmd(e,'LOBBY_BOTS');return e}
function start(){const e=setup();cmd(e,'START');return e}
function position(e,id,x,y){const p=e.state.player;p.inside=id;p.x=x;p.y=y}
function atObject(e,id,kind){const o=I.get(id).objects.find(x=>x.kind===kind);position(e,id,o.x+o.w/2,o.y+o.h+25);return o}
test('lobby rejects early start, duplicate member and incomplete ready',()=>{const e=new A.Engine();assert.equal(e.dispatch('START').ok,false);cmd(e,'LOBBY_CREATE',{name:'Partido'});const id=e.state.politics.parties[0].id;cmd(e,'LOBBY_ASSIGN',{party:id,slot:'president',player:'player'});assert.equal(e.dispatch('LOBBY_ASSIGN',{party:id,slot:'judge',player:'player'}).ok,false);assert.equal(e.dispatch('LOBBY_READY',{party:id}).ok,false)});
test('exact pairs start campaign without government or chamber',()=>{const e=start();assert.equal(e.state.politics.president.id,null);assert.equal(e.state.politics.judge.id,null);assert.equal(e.state.politics.legislators.length,0);assert.equal(e.state.session.phase,'CAMPAIGN');assert.ok(e.state.politics.parties.every(p=>p.members.length===2));assert.ok(Object.values(e.state.players).every(p=>p.role==='CIVIL'))});
test('physical entry, collision, door and exit require locations',()=>{const e=start();const b=D.buildings.find(b=>b.id==='congress');position(e,null,b.x+b.w/2,b.y+b.h+20);cmd(e,'ENTER',{id:'congress'});assert.equal(e.state.player.x,500);assert.equal(e.state.player.y,675);position(e,'congress',500,570);assert.equal(e.dispatch('MOVE',{x:500,y:545}).ok,false);cmd(e,'DOOR',{id:'Acceso interior'});cmd(e,'MOVE',{x:500,y:545});cmd(e,'MOVE',{x:500,y:520});assert.equal(e.dispatch('EXIT').ok,false);position(e,'congress',500,680);cmd(e,'EXIT');assert.equal(e.state.player.inside,null)});
test('campaign physical proximity and election assigns president judge seats',()=>{const e=start();assert.equal(e.dispatch('CAMPAIGN').ok,false);atObject(e,'plaza','campaign');cmd(e,'CAMPAIGN');cmd(e,'ADVANCE',{days:7});assert.equal(e.state.session.phase,'BALLOT');atObject(e,'plaza','ballot');cmd(e,'BALLOT',{party:e.state.player.party});assert.equal(e.dispatch('BALLOT',{party:e.state.player.party}).ok,false);cmd(e,'ADVANCE',{days:2});assert.ok(e.state.politics.president.id);assert.ok(e.state.politics.judge.id);assert.notEqual(e.state.politics.president.id,e.state.politics.judge.id);assert.equal(e.state.politics.legislators.length,21);assert.equal(e.state.politics.elections[0].cast+e.state.politics.elections[0].abstentions,10000)});
test('law still changes taxation through chamber after election',()=>{const e=start();cmd(e,'ADVANCE',{days:9});atObject(e,'congress','congress');cmd(e,'PROPOSE',{key:'tax',value:.25});cmd(e,'ADVANCE',{days:2});const b=e.state.politics.bills[0];assert.equal(b.status,'EXECUTIVE');const president=e.state.politics.president.id;e.switchActor(president);atObject(e,'congress','executive');cmd(e,'EXECUTIVE',{id:b.id});assert.equal(e.state.policy.tax,.25)});
test('actor-specific judge permissions remain separated',()=>{const e=start();cmd(e,'ADVANCE',{days:9});e.switchActor(e.state.politics.president.id);atObject(e,'court','justice');assert.equal(e.dispatch('VERDICT',{id:1,decision:'ACQUIT'}).ok,false);assert.equal(e.dispatch('JOB',{job:'judge'}).ok,false)});
test('physical shelf to cart to checkout conserves money and stock',()=>{const e=start();const shelf=atObject(e,'market','shelf');const initial=e.state.player.inventory[shelf.product];cmd(e,'CART_ADD',{id:shelf.id});atObject(e,'market','market');cmd(e,'CHECKOUT');assert.equal(e.state.player.inventory[shelf.product],initial+1);assert.equal(e.state.world.stock.market[shelf.product],59);assert.deepEqual(e.state.player.cart,{})});
test('projectile damages actor, records legal case, saves and loads',()=>{const e=start();atObject(e,'police','armory');cmd(e,'TEST_KIT');cmd(e,'EQUIP',{id:'pistol'});position(e,null,820,810);cmd(e,'ATTACK',{x:870,y:810});cmd(e,'PHYSICS',{dt:.05});cmd(e,'PHYSICS',{dt:.05});assert.equal(e.state.world.actors.outside[0].health,72);assert.equal(e.state.justice.cases.length,1);assert.equal(e.state.justice.cases[0].suspect,'player');assert.equal(e.state.player.ammo.magazine,5);const loaded=start();assert.ok(loaded.load(e.save()).ok);assert.equal(loaded.save(),e.save())});
test('melee limited range and reload consume inventory ammunition',()=>{const e=start();atObject(e,'police','armory');cmd(e,'TEST_KIT');cmd(e,'EQUIP',{id:'knife'});position(e,null,825,810);cmd(e,'ATTACK',{x:870,y:810});assert.equal(e.state.world.actors.outside[0].health,82);cmd(e,'PHYSICS',{dt:.1});e.state.player.weaponCooldown=0;cmd(e,'EQUIP',{id:'pistol'});cmd(e,'ATTACK',{x:1100,y:700});e.state.player.weaponCooldown=0;cmd(e,'RELOAD');assert.equal(e.state.player.ammo.magazine,6);assert.equal(e.state.player.ammo.reserve,17)});
test('real ball impulse goal and reset, no score button',()=>{const e=start();position(e,'pitch',500,650);cmd(e,'FOOTBALL_START',{mode:'practice'});position(e,'pitch',990,340);e.state.football.ball={x:1012,y:340,vx:0,vy:0};cmd(e,'KICK',{x:1080,y:340});for(let i=0;i<10;i++)cmd(e,'PHYSICS',{dt:.05});assert.equal(e.state.football.score[0],1);for(let i=0;i<50;i++)cmd(e,'PHYSICS',{dt:.05});assert.equal(e.state.football.ball.x,550);assert.equal(e.state.football.score[0],1)});
test('legal chain moves physical actor through detention court locked cell release',()=>{const e=start();atObject(e,'market','market');cmd(e,'CRIME',{crime:'theft'});cmd(e,'ADVANCE',{days:1});assert.equal(e.state.player.inside,'police');assert.equal(e.dispatch('EXIT').ok,false);cmd(e,'ADVANCE',{days:2});assert.equal(e.state.player.legal,'PRISONER');assert.equal(e.state.player.inside,'jail');assert.equal(e.dispatch('DOOR',{id:'C1'}).ok,false);cmd(e,'ADVANCE',{days:3});assert.equal(e.state.player.legal,'FREE');assert.equal(e.state.player.inside,'jail');assert.equal(e.state.justice.cases[0].status,'RELEASED')});
test('command envelopes reject stale and repeated commands',()=>{const e=start();const x={actorId:'player',commandId:'one',expectedRevision:e.state.session.revision,type:'ADVANCE',args:{days:1}};assert.ok(e.submit(x).ok);assert.equal(e.submit(x).ok,false);assert.equal(e.submit({...x,commandId:'two'}).ok,false)});
test('long-run shared world maintains balances and deterministic saves',()=>{const e=start();for(let i=0;i<4;i++)cmd(e,'ADVANCE',{days:60});assert.ok(A.validate(e.state));const load=new A.Engine();assert.ok(load.load(e.save()).ok);assert.equal(load.save(),e.save())});
test('configured seats and campaign duration determine the actual result',()=>{const e=setup();cmd(e,'LOBBY_CONFIG',{seats:100,campaignDays:3,termLength:30});cmd(e,'START');assert.equal(e.state.politics.nextElection,6);cmd(e,'ADVANCE',{days:5});assert.equal(e.state.politics.legislators.length,100);assert.equal(e.state.politics.elections[0].seats.reduce((a,r)=>a+r.count,0),100);assert.equal(e.state.politics.nextElection,36)});
test('single-party duplication and dropping an equipped weapon cannot bypass rules',()=>{const e=start();atObject(e,'police','armory');cmd(e,'TEST_KIT');cmd(e,'EQUIP',{id:'pistol'});cmd(e,'DROP',{id:'pistol'});assert.equal(e.state.player.equipped,null);assert.equal(e.dispatch('ATTACK',{x:300,y:300}).ok,false);assert.equal(e.dispatch('TEST_KIT').ok,false)});
test('sitting occupies physical seat, movement waits for standing',()=>{const e=start();const seat=atObject(e,'congress','seat'),before={x:e.state.player.x,y:e.state.player.y};cmd(e,'SIT',{id:seat.id});assert.equal(e.state.player.x,seat.x+seat.w/2);assert.equal(e.dispatch('MOVE',{x:e.state.player.x+4,y:e.state.player.y}).ok,false);cmd(e,'SIT');assert.equal(e.state.player.x,before.x);assert.equal(e.state.player.y,before.y)});
test('closing door on an actor is prevented',()=>{const e=start();position(e,'congress',500,570);cmd(e,'DOOR',{id:'Acceso interior'});cmd(e,'MOVE',{x:500,y:545});assert.equal(e.dispatch('DOOR',{id:'Acceso interior'}).ok,false);assert.equal(e.state.world.doors.congress['Acceso interior'],true)});
test('corrupted state import is rejected without replacing a valid game',()=>{const e=start(),before=e.save(),broken=JSON.parse(before);broken.state.policy.tax=99;assert.equal(e.load(JSON.stringify(broken)).ok,false);assert.equal(e.save(),before);broken.state.policy.tax=.21;broken.state.players.player.inside='missing';assert.equal(e.load(JSON.stringify(broken)).ok,false);assert.equal(e.save(),before)});
