// API integration tests with explicit media doubles. These are NOT acoustic/browser tests.
const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function harness(){const elements=new Map(),sent=[],events={},tracks=[{enabled:true,stop(){this.stopped=true}}],stream={getAudioTracks:()=>tracks,getTracks:()=>tracks};
 const el=()=>({innerHTML:'',textContent:'',value:'',dataset:{},style:{},options:[]});const document={getElementById:id=>{if(!elements.has(id))elements.set(id,el());return elements.get(id)},createElement:()=>el(),body:{appendChild(){}},addEventListener(){}};
 class Node{constructor(){this.gain={value:1,setTargetAtTime(v){this.value=v}};this.pan={value:0,setTargetAtTime(v){this.value=v}}}connect(dest){this.dest=dest}disconnect(){}getByteTimeDomainData(a){a.fill(128)}}
 class AudioContext{constructor(){this.currentTime=0;this.destination={}}resume(){return Promise.resolve()}close(){return Promise.resolve()}createAnalyser(){return new Node()}createMediaStreamSource(s){assert.ok(s);return new Node()}createGain(){return new Node()}createStereoPanner(){return new Node()}}
 class Peer{constructor(config){this.config=config;this.connectionState='new';this.tracks=[];this.candidates=[]}addTrack(t,s){this.tracks.push(t);assert.equal(s,stream)}async createOffer(){return{type:'offer',sdp:'mock-offer'}}async createAnswer(){return{type:'answer',sdp:'mock-answer'}}async setLocalDescription(d){this.localDescription={...d,toJSON:()=>d}}async setRemoteDescription(d){this.remoteDescription=d}async addIceCandidate(c){this.candidates.push(c)}close(){this.closed=true}setConfiguration(c){this.config=c}}
 const net={connected:true,identity:{actorId:'a'},on:(k,f)=>events[k]=f,send:m=>{sent.push(m);return true},state:{session:{phase:'CAMPAIGN'},player:{id:'a',inside:'congress',x:100,y:100},players:{b:{id:'b',inside:'congress',x:160,y:100}}}};
 const context={document,navigator:{mediaDevices:{getUserMedia:async()=>stream}},RTCPeerConnection:Peer,AudioContext,Audio:class{play(){return Promise.resolve()}pause(){}},MediaStream:class{},console,setInterval:()=>1,clearInterval(){},addEventListener(){},Uint8Array,Date};context.globalThis=context;vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../src/voice.js'),'utf8'),context);const voice=new context.ArgentumVoice(net);voice.mount();return{voice,net,tracks,sent,context,events};}

test('voice integrates capture, offer/answer/ICE, remote audio, distance, scene, mute and mic/PTT',async()=>{const h=harness(),v=h.voice;await v.start();assert.equal(v.enabled,true);assert.equal(h.tracks[0].enabled,false,'PTT starts silent');v.pressed=true;v.applyMic();assert.equal(h.tracks[0].enabled,true);
 v.allowed.set('b',{id:'b',epoch:1,name:'Bruno'});await v.offer({id:'b',epoch:1});const peer=v.peers.get('b');assert.equal(peer.pc.tracks.length,1);assert.ok(h.sent.some(m=>m.kind==='signal'&&m.signal.description.type==='offer'));
 await v.signal({from:'b',epoch:1,signal:{candidate:{candidate:'mock-ice'}}});assert.equal(peer.pending.length,1);await v.signal({from:'b',epoch:1,signal:{description:{type:'answer',sdp:'mock-answer'}}});assert.equal(peer.pc.candidates.length,1);
 peer.pc.ontrack({streams:[{mockRemote:true}]});v.update();assert.ok(Math.abs(peer.gain.gain.value-.6)<.001,'distance 60 / range240 gives gain .8*.75');assert.equal(peer.pan.pan.value,.25);
 h.net.state.players.b.x=400;v.update();assert.equal(peer.gain.gain.value,0);h.net.state.players.b.x=100;h.net.state.players.b.inside='market';v.update();assert.equal(peer.gain.gain.value,0,'same coords in different scene is silent');
 h.net.state.players.b.inside='congress';v.muted.add('b');v.update();assert.equal(peer.gain.gain.value,0);v.muted.clear();v.update();assert.equal(peer.gain.gain.value,.8);
 v.mic=false;v.applyMic();assert.equal(h.tracks[0].enabled,false);v.reconcile([]);assert.equal(peer.pc.closed,true);assert.equal(v.peers.size,0);v.stop();assert.equal(h.tracks[0].stopped,true);
});

test('microphone denial leaves gameplay connected; Congress waits for server floor',async()=>{const h=harness();h.context.navigator.mediaDevices.getUserMedia=async()=>{const e=Error('denied');e.name='NotAllowedError';throw e};await h.voice.start();assert.equal(h.voice.enabled,false);assert.equal(h.net.connected,true);assert.match(h.voice.status,/denegado/);
 const x=harness();await x.voice.start();x.voice.channel='CONGRESS';x.voice.pressed=true;x.voice.applyMic();assert.equal(x.tracks[0].enabled,false);assert.ok(x.sent.some(m=>m.channel==='CONGRESS'&&m.speaking));x.voice.turn='a';x.voice.reconcile([]);assert.equal(x.tracks[0].enabled,true);x.voice.stop();
});

test('leaving while mic permission is pending closes late capture and duplicate clicks do not capture twice',async()=>{const h=harness();let resolve,calls=0;h.context.navigator.mediaDevices.getUserMedia=()=>{calls++;return new Promise(r=>resolve=r)};const pending=h.voice.start();await h.voice.start();assert.equal(calls,1);h.voice.stop();resolve({getTracks:()=>h.tracks,getAudioTracks:()=>h.tracks});await pending;assert.equal(h.voice.enabled,false);assert.equal(h.tracks[0].stopped,true);assert.equal(h.voice.stream,null);});
