(function(G){
if(typeof require!=='undefined'){G.ArgentumGovernance=G.ArgentumGovernance||require('./governance.js');G.ArgentumData=G.ArgentumData||require('./data.js');G.ArgentumInteriors=G.ArgentumInteriors||require('./interiors.js');G.ArgentumLobby=G.ArgentumLobby||require('./lobby.js');G.ArgentumPhysical=G.ArgentumPhysical||require('./physical.js')}
const D=G.ArgentumData||(typeof require!=='undefined'?require('./data.js'):null),C=(v,a,b)=>Math.max(a,Math.min(b,v)),R=v=>Math.round(v*100)/100,copy=x=>JSON.parse(JSON.stringify(x));
function check(v,m){if(!v)throw Error(m)}
function rng(s){s.seed=(Math.imul(s.seed,1664525)+1013904223)>>>0;return s.seed/4294967296}
function news(s,title,body,category='ciudad'){s.news.unshift({id:++s.seq,day:s.time.day,title,body,category});s.news=s.news.slice(0,120)}
function newGame(name='Ciudadano'){
 name=name.trim().slice(0,32)||'Ciudadano';const role='CIVIL';
 const s={version:2,seed:73921,seq:0,time:{day:1,speed:0},player:{id:'player',name,money:100000,health:100,hunger:90,hydration:90,energy:95,role,party:null,inventory:{water:3,food:2,medicine:1,mate:0,extinguisher:0},hotbar:D.products.map(p=>p.id),properties:[],job:null,legal:'FREE',x:925,y:815,inside:null,reputation:50,lastWork:0,lastFootball:0,training:[]},accounts:{player:100000,treasury:350000,population:3000000,market:150000,external:8000000,propertyBank:2000000},economy:{activity:100,employment:91,inflation:2.4,priceIndex:1,confidence:60,poverty:22,debt:120000,interest:.025,reserves:300000,emitted:0,revenue:0,spending:0,balance:0,consumption:0,healthQuality:70,securityQuality:65,history:[],moneyTotal:13600000},policy:{tax:.21,income:.1,property:.0002,health:1,security:1,penalty:5},politics:{parties:[],president:{id:null,name:'Sin Presidente electo',party:null,terms:0},legislators:[],bills:[],laws:[],elections:[],nextElection:28,campaign:{},poll:null,constitution:{termLength:90,maxTerms:2,quorum:.5,majority:.5,amendmentMajority:2/3,totalCycles:0}},society:{approval:57,previousApproval:57,sectors:D.sectors.map(g=>({...copy(g),satisfaction:57})),protest:false},world:{properties:{},stock:{market:Object.fromEntries(D.products.map(p=>[p.id,60]))}},justice:{cases:[],cells:Array.from({length:4},(_,i)=>({cellId:'C'+(i+1),doorState:'OPEN',locked:false,occupantPlayerId:null}))},events:[],drops:[],news:[],ledger:[],commands:[],goals:{law:false,election:false,purchase:false,justice:false},settings:{sound:false}};
 for(const b of D.buildings.filter(b=>b.kind==='property')){s.world.properties[b.id]={propertyId:b.id,type:'HOME_SHOP',ownerId:null,value:b.id[0]==='N'?65000:48000,forSale:true,price:b.id[0]==='N'?65000:48000,markup:1.15,storage:Object.fromEntries(D.products.map(p=>[p.id,0])),open:false};s.world.stock[b.id]=Object.fromEntries(D.products.map(p=>[p.id,0]));s.accounts[b.id]=0;}
 G.ArgentumLobby.initialize(s);G.ArgentumPhysical.initialize(s);G.ArgentumGovernance?.initialize(s);return s;
}
function transfer(s,from,to,amount,reason){amount=R(amount);check(Number.isFinite(amount)&&amount>=0,'Importe inválido');check(from in s.accounts&&to in s.accounts,'Cuenta inexistente');check(s.accounts[from]+.001>=amount,'Fondos insuficientes');s.accounts[from]=R(s.accounts[from]-amount);s.accounts[to]=R(s.accounts[to]+amount);for(const p of Object.values(s.players||{player:s.player}))p.money=s.accounts[p.id];s.player.money=s.accounts[s.player.id];s.ledger.unshift({id:++s.seq,day:s.time.day,from,to,amount,reason});s.ledger=s.ledger.slice(0,500);if(to==='treasury')s.economy.revenue+=amount;if(from==='treasury')s.economy.spending+=amount;}
function price(s,id,store='market'){const p=D.products.find(p=>p.id===id);check(p,'Producto inexistente');const stock=s.world.stock[store]?.[id]||0;return R(p.base*s.economy.priceIndex*(1+Math.max(0,15-stock)*.008)*(store==='market'?1:s.world.properties[store].markup)*(1+s.policy.tax))}
function at(s,id){check(s.player.inside===id,'Entrá al edificio correspondiente para realizar esta acción.');const room=G.ArgentumInteriors.get(id);check(room.objects.some(o=>['service','congress','executive','justice','market','police','jail','fire','property','hospital','bed','stock','campaign','armory'].includes(o.kind)&&G.ArgentumInteriors.near(s.player,o)),'Acercate al puesto de atención, atril, escritorio o caja.')}
function free(s){check(s.player.legal==='FREE','Tu situación judicial restringe esta acción.')}
function billScore(s,l,b){const p=s.politics.parties.find(p=>p.id===l.party),scale={tax:.16,health:.7,security:.7,penalty:7,weapons:1.5}[b.key];let v=.64-Math.abs(p[b.key]+l.offset-b.value)/scale;if(b.sponsor===l.party)v+=.12;if(b.key==='tax')v+=(s.economy.balance<0?.05:-.03)*(b.value>s.policy.tax?1:-1);if(b.packageHealth)v+=.1-Math.abs(p.health-b.packageHealth)/1.5;if(b.blockStance?.[l.party])v+=b.blockStance[l.party]==='YES'?.14:b.blockStance[l.party]==='NO'?-.14:0;return v}
function predicted(s,b){return s.politics.legislators.map(l=>{const v=billScore(s,l,b);return{id:l.id,name:l.name,party:l.party,vote:v>.27?'YES':v>.19?'ABSTAIN':'NO'}})}
function enact(s,b){check(!b.effectiveDate,'La ley ya está vigente');s.policy[b.key]=b.value;if(b.packageHealth)s.policy.health=b.packageHealth;b.status='ENACTED';b.effectiveDate=s.time.day;s.politics.laws.push(copy(b));s.goals.law=true;news(s,'Nueva ley: '+b.title,'Rige desde hoy: '+D.laws[b.key].name+' = '+R(b.value*D.laws[b.key].factor)+D.laws[b.key].unit+'.','congreso')}
function tally(s,b,override=false){const votes=override?b.overrideVotes:b.votes,yes=votes.filter(v=>v.vote==='YES').length,no=votes.filter(v=>v.vote==='NO').length,total=s.politics.legislators.length,quorum=votes.length>total*s.politics.constitution.quorum,passed=quorum&&(override?yes>=Math.ceil(total*2/3):yes>(yes+no)*s.politics.constitution.majority);b.result={yes,no,abstain:votes.length-yes-no,quorum,passed};if(passed){if(override)enact(s,b);else{b.status='EXECUTIVE';b.executiveDay=s.time.day+1;news(s,'El Congreso aprueba '+b.title,yes+' votos afirmativos. Pasa al Poder Ejecutivo.','congreso')}}else{b.status='REJECTED';news(s,'Proyecto rechazado',b.title+': '+yes+' a favor y '+no+' en contra.','congreso')}}
function electoralWeights(s){return s.politics.parties.map(p=>{let value=0;for(const g of s.society.sectors){const distance=g.ideology.reduce((a,v,i)=>a+Math.abs(v-p.ideology[i]),0)/6;value+=g.weight*Math.max(1,50-distance*35+(p.id===s.politics.president.party?(g.satisfaction-50)*.65:(50-g.satisfaction)*.13)+(s.politics.campaign[p.id]||0)*.7+(s.governance?.credibility[p.id]||0))}return{party:p.id,value:G.ArgentumLobby.eligible(s,p)?value:0}})}
function poll(s){const values=electoralWeights(s).map(p=>({...p,value:p.value*(.94+rng(s)*.12)})),sum=values.reduce((a,p)=>a+p.value,0);s.politics.poll={day:s.time.day,margin:3,values:values.map(p=>({...p,value:R(p.value/sum*100)}))}}
function election(s){G.ArgentumLobby.election(s);poll(s)}
function verdict(s,c,decision){check(c?.status==='TRIAL','El caso no está en juicio');check(['ACQUIT','CONVICT'].includes(decision),'Decisión inválida');const defendant=s.players[c.suspect];if(decision==='ACQUIT'){check(c.evidence<.75,'La evidencia corroborada requiere una decisión fundada de condena');c.status='ACQUITTED';if(defendant){defendant.legal='FREE';defendant.role=c.previousRole;G.ArgentumPhysical.warp(s,defendant,'court',{x:500,y:655})}s.goals.justice=true;news(s,'Absolución','Caso '+c.id+': prueba insuficiente.','justicia');return}check(c.evidence>=.6,'No hay prueba suficiente para condenar');const cell=s.justice.cells.find(x=>!x.occupantPlayerId);check(cell,'No hay celdas libres');c.status='CONVICTED';c.sentence=Math.min(s.policy.penalty,c.crime==='theft'?3:5);c.releaseDay=s.time.day+c.sentence;c.cellId=cell.cellId;Object.assign(cell,{occupantPlayerId:c.suspect,locked:true,doorState:'LOCKED'});if(defendant){defendant.legal='PRISONER';defendant.role='PRISONER';const index=Number(cell.cellId.slice(1))-1;G.ArgentumPhysical.warp(s,defendant,'jail',{x:145+index*238,y:350})}news(s,'Sentencia dictada','Caso '+c.id+': '+c.sentence+' días. Celda '+cell.cellId+'.','justicia');}
function daily(s){s.time.day++;const e=s.economy,p=s.player;e.revenue=0;e.spending=0;e.consumption=0;
 G.ArgentumGovernance?.daily(s,news);
 const demand=C(1-(s.policy.tax-.21)*2.1+(e.confidence-60)/230,.45,1.4),production=C(e.activity/100,.4,1.5),goods=R(Math.min(s.accounts.population*.012,12500*demand*production));if(goods>0){const tax=R(goods*s.policy.tax/(1+s.policy.tax));transfer(s,'population','market',goods-tax,'Consumo agregado');transfer(s,'population','treasury',tax,'Impuesto al consumo');e.consumption=goods}
 const wages=R(Math.min(s.accounts.market*.1,10500*production));transfer(s,'market','population',wages,'Salarios privados');
 const costs=R(5200*s.policy.health+3900*s.policy.security+3400+e.debt*e.interest/30);if(s.accounts.treasury<costs){const credit=R(costs-s.accounts.treasury+10000);if(s.accounts.external>=credit){transfer(s,'external','treasury',credit,'Financiamiento de deuda');e.debt+=credit;e.revenue-=credit}}
 transfer(s,'treasury','population',Math.min(costs,s.accounts.treasury),'Servicios públicos e intereses');transfer(s,'market','treasury',R(Math.min(s.accounts.market,Math.max(0,goods-wages)*.12)),'Impuesto empresarial');
 for(const [id,prop] of Object.entries(s.world.properties))if(prop.ownerId){const owner=prop.ownerId;const tax=R(prop.value*s.policy.property);if(s.accounts[owner]>=tax)transfer(s,owner,'treasury',tax,'Tasa inmobiliaria '+id);if(prop.open)for(const item of D.products)if(s.world.stock[id][item.id]>0&&s.accounts.population>=price(s,item.id,id)&&rng(s)<C(1.7-prop.markup*.5-(s.policy.tax-.21)*1.5,.05,1)){const amount=price(s,item.id,id),tax=R(amount*s.policy.tax/(1+s.policy.tax));transfer(s,'population',id,amount-tax,'Venta '+item.name);transfer(s,'population','treasury',tax,'Consumo '+id);s.world.stock[id][item.id]--;e.consumption+=amount}}
 for(const item of D.products)if(s.world.stock.market[item.id]<60){const units=Math.min(10,60-s.world.stock.market[item.id]),cost=R(item.base*.6*units*e.priceIndex);if(s.accounts.market>=cost){transfer(s,'market','external',cost,'Proveedor '+item.name);s.world.stock.market[item.id]+=units}}
 e.balance=R(e.revenue-e.spending);const conf=C(64-(s.policy.tax-.18)*100-e.inflation*1.3+e.healthQuality*.1-e.debt/300000,15,90);e.confidence+=(conf-e.confidence)*.055;e.activity+=(C(95+(G.ArgentumGovernance?.bonus(s,'activity')||0)+(e.confidence-50)*.3-(s.policy.tax-.2)*60,55,130)-e.activity)*.065;e.employment+=(C(88+(e.activity-90)*.28,60,98)-e.employment)*.08;const pressure=C(.8+Math.max(0,-e.balance)/14000+e.emitted/400000+(e.activity-100)*.025,0,18);e.inflation+=(pressure-e.inflation)*.05;e.priceIndex*=1+e.inflation/3000;e.healthQuality+=(C(s.policy.health*65+(G.ArgentumGovernance?.bonus(s,'healthQuality')||0),25,100)-e.healthQuality)*.1;e.securityQuality+=(C(s.policy.security*65+(G.ArgentumGovernance?.bonus(s,'securityQuality')||0),25,100)-e.securityQuality)*.1;e.poverty=C(22+(91-e.employment)*1.2+(e.priceIndex-1)*15,4,70);
 s.society.previousApproval=s.society.approval;for(const g of s.society.sectors){const factors=[C(60+(e.employment-90)*3-e.inflation*3,5,95),e.healthQuality,e.securityQuality,e.confidence],target=g.priorities.reduce((a,w,i)=>a+w*factors[i],0);g.satisfaction+=(target-g.satisfaction)*.12}s.society.approval=s.society.sectors.reduce((a,g)=>a+g.weight*g.satisfaction,0);const protest=s.society.approval<42;if(protest&&!s.society.protest)news(s,'Manifestación en la plaza','Los hogares reclaman por precios y servicios.','sociedad');s.society.protest=protest;
 for(const person of Object.values(s.players)){person.hunger=C(person.hunger-2,0,100);person.hydration=C(person.hydration-3,0,100);person.energy=C(person.energy-1,0,100);if(person.hunger<15||person.hydration<15)person.health=C(person.health-2,1,100);if(person.legal!=='FREE'){person.hunger=Math.max(person.hunger,55);person.hydration=Math.max(person.hydration,60)}}
 for(const b of s.politics.bills){if(b.status==='COMMITTEE'&&s.time.day>=b.voteDay){b.status='VOTING';b.votes=predicted(s,b).filter(v=>v.id!=='player');if(!s.politics.legislators.some(l=>l.id==='player'))tally(s,b);else news(s,'Tu banca tiene la palabra','Votá '+b.title+' en el Congreso.','congreso')}if(b.status==='VOTING'&&s.time.day>b.voteDay+2){b.votes.push({id:'player',name:p.name,party:p.party,vote:'ABSTAIN'});tally(s,b)}if(b.status==='EXECUTIVE'&&s.time.day>=b.executiveDay&&s.players[s.politics.president.id]?.isBot){if(billScore(s,{party:s.politics.president.party,offset:0},b)>-.15)enact(s,b);else{b.status='VETOED';news(s,'Veto presidencial',b.title+' vuelve al Congreso. Puede insistir con dos tercios.','congreso')}}}
 G.ArgentumPhysical.legalDaily(s,verdict);
 if(s.time.day%6===0&&s.justice.cases.filter(c=>!['ACQUITTED','RELEASED'].includes(c.status)).length<4&&rng(s)>s.economy.securityQuality/150){const suspect=['Vecino R. Luna','Vecina M. Prado','Vecino D. Torres'][Math.floor(rng(s)*3)]+' #'+s.time.day;const theft=rng(s)>.35;s.justice.cases.push({id:++s.seq,crime:theft?'theft':'damage',suspect,reason:theft?'denuncia comercial y registro de cámara':'denuncia vecinal sin corroboración',evidence:theft?.85:.45,status:'INVESTIGATION',nextDay:s.time.day+2,previousRole:'CIVIL'});news(s,'Nueva denuncia vecinal','La comisaría abre una investigación. La prevención depende del servicio de seguridad.','justicia')}
 if(s.time.day%9===0&&!s.events.some(x=>x.status==='ACTIVE')){const ids=Object.keys(s.world.properties),location=ids[Math.floor(rng(s)*ids.length)];s.events.push({id:++s.seq,type:'fire',location,status:'ACTIVE',intensity:3,day:s.time.day});news(s,'Incendio en '+location,'Desperfecto eléctrico. El cuartel recibe la emergencia.','emergencia')}
 for(const ev of s.events.filter(x=>x.status==='ACTIVE'))if(s.time.day-ev.day>=4){ev.status='RESOLVED';e.confidence=C(e.confidence-2,0,100);news(s,'Bomberos controló el incendio','Daños materiales en '+ev.location+'.','emergencia')}
 if(s.time.day%2===0)poll(s);if(s.time.day%7===0){poll(s);news(s,'El pulso de la economía','Actividad '+e.activity.toFixed(1)+' · inflación mensual '+e.inflation.toFixed(1)+'% · aprobación '+s.society.approval.toFixed(1)+'%.','economía')}
 if(s.session.phase==='GOVERNMENT'&&s.time.day>=s.politics.nextElection-s.session.campaignDays-s.session.ballotDays)s.session.phase='CAMPAIGN';if(s.time.day>=s.politics.nextElection-s.session.ballotDays&&s.time.day<s.politics.nextElection)s.session.phase='BALLOT';if(s.time.day>=s.politics.nextElection)election(s);
 G.ArgentumGovernance?.review(s,news);
 e.history.push({day:s.time.day,tax:s.policy.tax,activity:e.activity,inflation:e.inflation,approval:s.society.approval,balance:e.balance,price:price(s,'food')});e.history=e.history.slice(-120);
}
function run(s,type,a){const p=s.player;if(G.ArgentumLobby.run(s,type,a))return;check(s.session.phase!=='LOBBY','Completá el lobby primero');if(G.ArgentumGovernance?.run(s,type,a,{transfer,news}))return;if(G.ArgentumPhysical.run(s,type,a))return;const required={PROPOSE:['congress'],AMEND:['congress'],BLOCK_STANCE:['congress'],OVERRIDE:['congress'],EXECUTIVE:['executive'],VERDICT:['justice'],BUY:['market','property'],CHECKOUT:['market']};if(required[type])check(p.inside&&G.ArgentumInteriors.get(p.inside).objects.some(o=>required[type].includes(o.kind)&&G.ArgentumInteriors.near(p,o)),'Acercate al puesto correspondiente: '+required[type].join(' / '));switch(type){
case 'ADVANCE':check(Number.isInteger(a.days)&&a.days>0&&a.days<=120,'Cantidad de días inválida');for(let i=0;i<a.days;i++)daily(s);break;
case 'BUY':{free(s);const store=a.store||'market';at(s,store);check(s.world.stock[store],'No es un comercio');if(store!=='market')check(s.world.properties[store].open,'El comercio está cerrado');const q=a.quantity||1;check(Number.isInteger(q)&&q>0&&q<=99,'Cantidad inválida');check(s.world.stock[store][a.id]>=q,'No hay stock');const total=R(price(s,a.id,store)*q),tax=R(total*s.policy.tax/(1+s.policy.tax));check(s.accounts[p.id]>=total,'No te alcanza el dinero');transfer(s,p.id,store,total-tax,'Compra '+a.id);transfer(s,p.id,'treasury',tax,'Impuesto al consumo');s.world.stock[store][a.id]-=q;p.inventory[a.id]+=q;s.goals.purchase=true;break}
case 'USE':{const item=D.products.find(i=>i.id===a.id);check(item&&a.id!=='extinguisher','El extintor se usa en una emergencia');check(p.inventory[a.id]>0,'No tenés ese producto');p.inventory[a.id]--;for(const key of ['health','hunger','hydration','energy'])if(item[key])p[key]=C(p[key]+item[key],0,100);break}
case 'DROP':free(s);check(p.inventory[a.id]>0,'No tenés ese producto');p.inventory[a.id]--;if(p.equipped===a.id&&!p.inventory[a.id])p.equipped=null;s.drops.push({id:++s.seq,product:a.id,x:p.x,y:p.y,inside:p.inside});break;
case 'PICKUP':{free(s);const item=s.drops.find(d=>d.id===a.id);check(item&&item.inside===p.inside&&Math.hypot(p.x-item.x,p.y-item.y)<60,'Objeto fuera de alcance');p.inventory[item.product]=(p.inventory[item.product]||0)+1;s.drops=s.drops.filter(d=>d.id!==a.id);break}
case 'PROPOSE':{free(s);check(s.politics.president.id,'Todavía no hay gobierno electo ni Congreso constituido');at(s,'congress');const def=D.laws[a.key];check(def,'Ley desconocida');check(Number.isFinite(a.value)&&a.value*def.factor>=def.min&&a.value*def.factor<=def.max,'Valor fuera de límites');check(s.politics.bills.filter(b=>['COMMITTEE','VOTING','EXECUTIVE'].includes(b.status)).length<5,'Ya hay cinco proyectos en trámite');s.politics.bills.unshift({revision:1,versions:[{revision:1,day:s.time.day,author:p.id,value:a.value,packageHealth:null}],id:++s.seq,title:(a.title||def.name).slice(0,80),key:a.key,value:a.value,status:'COMMITTEE',author:p.id,sponsor:p.party,votes:[],created:s.time.day,voteDay:s.time.day+2,effectiveDate:null,packageHealth:null});news(s,'Proyecto ciudadano presentado',def.name+': comisión y debate durante dos días.','congreso');break}
case 'AMEND':{free(s);at(s,'congress');const b=s.politics.bills.find(b=>b.id===a.id);check(b?.status==='COMMITTEE','La comisión ya cerró');const def=D.laws[b.key];check(Number.isFinite(a.value)&&a.value*def.factor>=def.min&&a.value*def.factor<=def.max,'Valor fuera de límites');b.value=a.value;if(a.packageHealth!==undefined){check(a.packageHealth===null||a.packageHealth>=.6&&a.packageHealth<=1.6,'Paquete inválido');b.packageHealth=a.packageHealth}G.ArgentumGovernance?.revise(s,b);break}
case 'VOTE':{free(s);at(s,'congress');const b=s.politics.bills.find(b=>b.id===a.id);check(p.role==='LEGISLATOR'&&s.politics.legislators.some(l=>l.id===p.id),'Solo legisladores pueden votar');check(b?.status==='VOTING','No hay votación abierta');check(!b.votes.some(v=>v.id===p.id),'Ya emitiste tu voto');check(['YES','NO','ABSTAIN'].includes(a.vote),'Voto inválido');b.votes.push({id:p.id,name:p.name,party:p.party,vote:a.vote});tally(s,b);break}
case 'EXECUTIVE':{free(s);at(s,'congress');check(s.politics.president.id===p.id,'Facultad exclusiva del Presidente');const b=s.politics.bills.find(b=>b.id===a.id);check(b?.status==='EXECUTIVE','No espera decisión ejecutiva');if(a.veto){b.status='VETOED';news(s,'Veto presidencial',b.title+' no entra en vigencia.','congreso')}else enact(s,b);break}
case 'OVERRIDE':{free(s);at(s,'congress');const b=s.politics.bills.find(b=>b.id===a.id);check(b?.status==='VETOED','No hay veto que revisar');b.overrideVotes=predicted(s,b);tally(s,b,true);break}
case 'JOIN':case 'CREATE_PARTY':throw Error('Los partidos se forman en el lobby y tienen exactamente dos integrantes.');
case 'CAMPAIGN':free(s);check(['CAMPAIGN','GOVERNMENT'].includes(s.session.phase),'La campaña está cerrada durante votación');check(s.player.inside&&G.ArgentumInteriors.get(s.player.inside).objects.some(o=>['campaign','property'].includes(o.kind)&&G.ArgentumInteriors.near(p,o)),'Acercate al acto en la plaza, al micrófono de debate o a la caja de un negocio');check(p.party,'Afiliate o creá un partido');check(p.lastCampaign!==s.time.day,'Ya realizaste campaña hoy');transfer(s,p.id,'population',1500,'Campaña pública');s.politics.campaign[p.party]=Math.min(45,(s.politics.campaign[p.party]||0)+4);p.lastCampaign=s.time.day;s.goals.campaign=true;p.energy=C(p.energy-5,0,100);break;
case 'BUY_PROPERTY':{free(s);at(s,a.id);const prop=s.world.properties[a.id];check(prop?.forSale&&!prop.ownerId,'Propiedad no disponible');transfer(s,p.id,'propertyBank',prop.price,'Escritura '+a.id);prop.ownerId=p.id;prop.forSale=false;p.properties.push(a.id);break}
case 'SELL_PROPERTY':{free(s);at(s,a.id);const prop=s.world.properties[a.id];check(prop?.ownerId===p.id,'No sos propietario');check(D.products.every(x=>s.world.stock[a.id][x.id]===0&&prop.storage[x.id]===0),'Retirá stock y objetos antes de vender');transfer(s,'propertyBank',p.id,prop.value*.9,'Venta '+a.id);if(s.accounts[a.id])transfer(s,a.id,p.id,s.accounts[a.id],'Liquidación comercio');prop.ownerId=null;prop.forSale=true;prop.open=false;p.properties=p.properties.filter(x=>x!==a.id);break}
case 'BUSINESS':{free(s);at(s,a.id);const prop=s.world.properties[a.id];check(prop?.ownerId===p.id,'No sos propietario');check(Number.isFinite(a.markup)&&a.markup>=.8&&a.markup<=2,'Margen permitido: 0,8 a 2');prop.markup=a.markup;prop.open=!!a.open;break}
case 'RESTOCK':{free(s);at(s,a.store);check(s.world.properties[a.store]?.ownerId===p.id,'No sos propietario');const item=D.products.find(p=>p.id===a.id);check(item,'Producto inválido');check(Number.isInteger(a.quantity)&&a.quantity>0&&a.quantity<=50,'Cantidad inválida');transfer(s,p.id,'external',R(item.base*.65*s.economy.priceIndex*a.quantity),'Proveedor '+a.store);s.world.stock[a.store][a.id]+=a.quantity;break}
case 'TAKE_STOCK':free(s);at(s,a.store);check(s.world.properties[a.store]?.ownerId===p.id,'No sos propietario');check(s.world.stock[a.store][a.id]>0,'Stock vacío');s.world.stock[a.store][a.id]--;p.inventory[a.id]++;break;
case 'WITHDRAW':free(s);at(s,a.id);check(s.world.properties[a.id]?.ownerId===p.id,'No sos propietario');transfer(s,a.id,p.id,s.accounts[a.id],'Retiro utilidades');break;
case 'STORAGE':{free(s);at(s,a.store);const prop=s.world.properties[a.store];check(prop?.ownerId===p.id,'No sos propietario');check(D.products.some(x=>x.id===a.id),'Producto inválido');const src=a.take?prop.storage:p.inventory,dest=a.take?p.inventory:prop.storage;check(src[a.id]>0,'No hay unidades');src[a.id]--;dest[a.id]++;break}
case 'REST':free(s);if(s.session.mode==='ONLINE'){check(p.lastRest!==s.time.day,'Ya descansaste hoy');p.lastRest=s.time.day;}check(p.inside==='plaza'||s.world.properties[p.inside]?.ownerId===p.id,'Descansá en la plaza o en tu casa');p.energy=C(p.energy+(p.inside==='plaza'?20:60),0,100);if(s.session.mode!=='ONLINE')daily(s);break;
case 'TRAIN':{free(s);check(a.job!=='judge','La candidatura judicial se forma en el lobby');const job=D.jobs[a.job];check(job,'Trabajo desconocido');at(s,job.at);check(!p.training.includes(a.job),'Capacitación ya completada');transfer(s,p.id,'population',1200,'Capacitación '+job.name);if(s.session.mode!=='ONLINE')daily(s);p.training.push(a.job);break}
case 'JOB':{free(s);check(a.job!=='judge','El cargo judicial se obtiene por elección');const job=D.jobs[a.job];check(job,'Trabajo inválido');at(s,job.at);check(!['PRESIDENT','JUDGE','LEGISLATOR'].includes(p.role),'No podés ejercer dos cargos a la vez');check(a.job==='employee'||p.training.includes(a.job),'Completá la capacitación primero');p.job=a.job;p.role=job.role;break}
case 'WORK':{free(s);const job=D.jobs[p.job];check(job,'Primero conseguí empleo');at(s,job.at);check(p.lastWork!==s.time.day,'Ya cumpliste el turno de hoy');check(p.energy>=20,'Necesitás descansar');const source=p.job==='employee'?'market':'treasury',tax=R(job.pay*s.policy.income);check(s.accounts[source]>=job.pay,'Tu empleador no tiene fondos');transfer(s,source,p.id,job.pay-tax,'Salario '+job.name);if(source!=='treasury')transfer(s,source,'treasury',tax,'Impuesto al ingreso');p.lastWork=s.time.day;p.energy-=14;break}
case 'TREAT':free(s);at(s,'hospital');transfer(s,p.id,'treasury',350,'Copago hospitalario');p.health=C(p.health+25+s.economy.healthQuality*.35,0,100);break;
case 'CRIME':{free(s);check(!s.justice.cases.some(c=>c.suspect===p.id&&!['ACQUITTED','RELEASED'].includes(c.status)),'Ya hay una causa abierta');check(['theft','assault','damage'].includes(a.crime),'Delito inválido');if(a.crime==='theft'){at(s,'market');transfer(s,'market',p.id,1500,'Dinero sustraído')}s.justice.cases.push({id:++s.seq,crime:a.crime,suspect:p.id,reason:a.crime==='theft'?'cámara de caja y testimonio':a.crime==='damage'?'denuncia de daño material':'denuncia y testigos',evidence:a.crime==='damage'?.55:.9,status:'INVESTIGATION',nextDay:s.time.day+1,previousRole:p.role});p.reputation=C(p.reputation-15,0,100);news(s,'Investigación abierta','Se registra evidencia y se notifica a la policía.','justicia');break}
case 'ARREST':{free(s);at(s,'police');check(p.role==='POLICE','Requiere rol de policía');const c=s.justice.cases.find(c=>c.id===a.id);check(c?.status==='INVESTIGATION','La investigación no está abierta');check(c.evidence>=.5,'No hay indicios suficientes para una detención anticipada');c.status='CHARGED';c.nextDay=s.time.day+1;c.arrestReason=c.reason;const suspect=s.players[c.suspect];if(suspect){suspect.legal='DETAINED';suspect.equipped=null;G.ArgentumPhysical.warp(s,suspect,'police',{x:840,y:450})}news(s,'Detención por orden fundada','Caso '+c.id+': '+c.reason+'.','justicia');break}
case 'VERDICT':free(s);at(s,'court');check(p.role==='JUDGE'&&s.politics.judge.id===p.id,'Solo el juez electo puede resolver');check(s.justice.cases.find(c=>c.id===a.id)?.suspect!==p.id,'No podés juzgar tu propia causa');verdict(s,s.justice.cases.find(c=>c.id===a.id),a.decision);break;
case 'FIRE':{free(s);check(p.role==='FIREFIGHTER','Requiere rol de bombero');const ev=s.events.find(x=>x.id===a.id&&x.status==='ACTIVE');check(ev,'Emergencia resuelta');at(s,ev.location);check(p.inventory.extinguisher>0,'Necesitás un extintor');p.extinguisherCharge=p.extinguisherCharge||3;p.extinguisherCharge--;ev.intensity-=1+(G.ArgentumGovernance?.bonus(s,'firePower')||0);if(!p.extinguisherCharge){p.inventory.extinguisher--;delete p.extinguisherCharge}if(ev.intensity<=0){ev.status='RESOLVED';p.reputation=C(p.reputation+5,0,100);news(s,'Incendio controlado',p.name+' intervino en '+ev.location+'.','emergencia')}break}
case 'CHECKOUT':{at(s,'market');const cart=Object.entries(p.cart).filter(([,q])=>q>0);check(cart.length,'El carrito está vacío');for(const [id,quantity] of cart)run(s,'BUY',{id,quantity});p.cart={};break}
case 'BLOCK_STANCE':{at(s,'congress');const b=s.politics.bills.find(x=>x.id===a.id);check(b?.status==='COMMITTEE','La comisión cerró');check(['YES','NO','ABSTAIN'].includes(a.vote),'Posición inválida');b.blockStance||={};b.blockStance[p.party]=a.vote;break}
default:throw Error('Comando desconocido: '+type);
}}
function validate(s){check(s?.version===2&&s.players&&s.session&&s.economy,'Guardado incompatible: esta edición requiere formato 2');G.ArgentumLobby.validate(s);G.ArgentumGovernance?.validate(s);check(['LOBBY','CAMPAIGN','BALLOT','GOVERNMENT'].includes(s.session.phase),'Fase inválida');check(Number.isInteger(s.session.seatCount)&&s.session.seatCount>=5&&s.session.seatCount<=100,'Bancas inválidas');check(s.session.judicialMethod==='WINNING_TICKET','Método judicial incompatible');for(const [key,def] of Object.entries(D.laws))check(Number.isFinite(s.policy[key])&&s.policy[key]*def.factor>=def.min&&s.policy[key]*def.factor<=def.max,'Política inválida: '+key);check(Number.isInteger(s.time.day)&&s.time.day>=1,'Calendario inválido');for(const [id,p] of Object.entries(s.players)){check(p.id===id&&Number.isFinite(p.x)&&Number.isFinite(p.y),'Jugador inválido');check(p.inside===null||D.buildings.some(b=>b.id===p.inside),'Interior desconocido');for(const key of ['health','hunger','hydration','energy'])check(Number.isFinite(p[key])&&p[key]>=0&&p[key]<=100,'Necesidad inválida');check(['FREE','DETAINED','TRIAL','PRISONER'].includes(p.legal),'Estado legal inválido');check(Number.isInteger(p.ammo.magazine)&&p.ammo.magazine>=0&&p.ammo.magazine<=6&&Number.isInteger(p.ammo.reserve)&&p.ammo.reserve>=0,'Munición inválida');check(Math.abs(s.accounts[id]-p.money)<.01,'Saldo inconsistente');for(const q of Object.values(p.inventory))check(Number.isInteger(q)&&q>=0,'Inventario inválido')}for(const q of Object.values(s.accounts))check(Number.isFinite(q)&&q>=-.001,'Cuenta inválida');check(Math.abs(Object.values(s.accounts).reduce((a,b)=>a+b,0)-s.economy.moneyTotal)<.1,'Dinero no conservado');check(s.politics.parties.every(p=>p.members.every(id=>s.players[id])),'Miembro inexistente');check(s.politics.legislators.length===(s.politics.president.id?s.session.seatCount:0),'Bancas inconsistentes');check(new Set(s.politics.legislators.map(l=>l.id)).size===s.politics.legislators.length,'Bancas duplicadas');for(const b of s.politics.bills)check(new Set(b.votes.map(v=>v.id)).size===b.votes.length,'Votos duplicados');for(const c of s.justice.cells)check(c.locked===(c.doorState==='LOCKED'),'Celda inválida');for(const box of Object.values(s.world.stock))for(const q of Object.values(box))check(Number.isInteger(q)&&q>=0,'Stock inválido');return true}
class Engine{
constructor(s){this.state=s||newGame();this.state.player=this.state.players[this.state.session.activeId];validate(this.state)}
switchActor(id){check(this.state.players[id],'Jugador inexistente');this.state.session.activeId=id;this.state.player=this.state.players[id];return {ok:true}}
dispatch(type,args={},actorId=this.state.session.activeId){const next=copy(this.state);try{check(next.players[actorId],'Actor desconocido');next.player=next.players[actorId];if(type==='START'||type==='LOBBY_CONFIG')check(actorId===next.session.hostId,'Acción exclusiva del anfitrión');run(next,type,args);G.ArgentumGovernance?.review(next,news);for(const p of Object.values(next.players))p.money=next.accounts[p.id];next.player=next.players[next.session.activeId];validate(next);next.session.revision++;if(!['MOVE','PHYSICS'].includes(type)){next.commands.push({id:++next.seq,day:next.time.day,actor:actorId,type,args});next.commands=next.commands.slice(-300)}this.state=next;return{ok:true}}catch(e){return{ok:false,error:e.message}}}
submit(envelope){if(!envelope||typeof envelope.actorId!=='string'||typeof envelope.commandId!=='string')return{ok:false,error:'Sobre de comando inválido'};const key=envelope.actorId+':'+envelope.commandId;if(this.state.session.received[key])return{ok:false,error:'Comando duplicado'};if(envelope.expectedRevision!==this.state.session.revision)return{ok:false,error:'Estado desactualizado'};const r=this.dispatch(envelope.type,envelope.args||{},envelope.actorId);if(r.ok)this.state.session.received[key]=true;return r}
save(){const s=copy(this.state);delete s.player;return JSON.stringify({format:'ARGENTUM_2D',version:2,state:s})}
load(json){try{check(json.length<10000000,'Archivo demasiado grande');const x=JSON.parse(json);check(x.format==='ARGENTUM_2D'&&x.version===2,'Esta edición carga únicamente partidas de formato 2');x.state.player=x.state.players[x.state.session.activeId];validate(x.state);this.state=x.state;return{ok:true}}catch(e){return{ok:false,error:e.message}}}}
G.Argentum={Engine,newGame,price,predicted,billScore,validate};if(typeof module!=='undefined')module.exports=G.Argentum;
})(globalThis);
