(function(G){'use strict';
const definitions={
 hospital_equipment:{name:'Equipamiento hospitalario',category:'SALUD',description:'Compra e instalación de equipos. Mejora gradual del servicio hospitalario.',authorityRequired:'PRESIDENT',requiresLaw:false,budgetCost:18000,implementationTime:3,duration:30,effect:{healthQuality:10},affectedGroups:['Pacientes','Personal de salud']},
 police_equipment:{name:'Equipamiento de prevención',category:'SEGURIDAD',description:'Renovar equipos operativos para mejorar prevención y respuesta del servicio policial.',authorityRequired:'PRESIDENT',requiresLaw:false,budgetCost:16000,implementationTime:3,duration:30,effect:{securityQuality:9},affectedGroups:['Vecinos','Comerciantes']},
 fire_equipment:{name:'Equipamiento de bomberos',category:'BOMBEROS',description:'Refuerzo temporal del equipamiento de respuesta. Cada intervención humana reduce más la intensidad de un incendio.',authorityRequired:'PRESIDENT',requiresLaw:false,budgetCost:12000,implementationTime:2,duration:30,effect:{firePower:1},affectedGroups:['Bomberos','Vecinos']},
 road_maintenance:{name:'Mantenimiento de infraestructura',category:'INFRAESTRUCTURA',description:'Contratar mantenimiento que mejora gradualmente las condiciones de actividad. El gasto reduce la tesorería.',authorityRequired:'PRESIDENT',requiresLaw:false,budgetCost:24000,implementationTime:5,duration:45,effect:{activity:6},affectedGroups:['Trabajadores','Negocios']}
};
const copy=x=>JSON.parse(JSON.stringify(x)),check=(x,m)=>{if(!x)throw Error(m)};
function initialize(s){s.governance||={schema:1,measures:[],promises:[],credibility:{},budget:{byArea:{},totalCommitted:0}};for(const b of s.politics.bills){if(!b.revision){b.revision=1;b.versions=[{revision:1,day:b.created,author:b.author,value:b.value,packageHealth:b.packageHealth||null}]}}return s.governance}
function near(s,kinds){return s.player.legal==='FREE'&&s.player.inside&&G.ArgentumInteriors.get(s.player.inside).objects.some(o=>kinds.includes(o.kind)&&G.ArgentumInteriors.near(s.player,o))}
function bonus(s,key){return(s.governance?.measures||[]).filter(m=>m.status==='ACTIVE').reduce((v,m)=>v+(definitions[m.policyId]?.effect[key]||0),0)}
function revise(s,b){b.revision=(b.revision||1)+1;b.versions||=[{revision:1,day:b.created,author:b.author,value:b.value}];b.versions.push({revision:b.revision,day:s.time.day,author:s.player.id,value:b.value,packageHealth:b.packageHealth||null});b.blockStance={};}
function mark(s,p,status,news){if(p.status===status)return;p.status=status;p.history.push({day:s.time.day,status});const impacts={FULFILLED:2,ABANDONED:-3,EXPIRED:-2,BLOCKED_CONGRESS:-.5,BLOCKED_EXECUTIVE:-.5};s.governance.credibility[p.party]=Math.max(-8,Math.min(8,s.governance.promises.filter(x=>x.party===p.party).reduce((v,x)=>v+(impacts[x.status]||0),0)));news(s,'Promesa: '+status,p.title,'política');}
function review(s,news){if(!s.governance)return;for(const p of s.governance.promises){if(['FULFILLED','ABANDONED','EXPIRED','NOT_ELECTED'].includes(p.status))continue;
 if(s.politics.constitution.totalCycles>p.cycle&&p.status==='CAMPAIGN'){if(s.politics.president.party===p.party&&s.politics.president.id===p.author){p.dueDay=s.politics.nextElection;mark(s,p,'IN_PROGRESS',news);}else mark(s,p,'NOT_ELECTED',news);}
 if(!['IN_PROGRESS','BLOCKED_CONGRESS','BLOCKED_EXECUTIVE'].includes(p.status))continue;const b=s.politics.bills.find(b=>b.id===p.billId);
 if(b?.status==='ENACTED'&&b.key===p.key&&Math.abs(b.value-p.value)<.00001&&Math.abs(s.policy[p.key]-p.value)<.00001){mark(s,p,'FULFILLED',news);continue;}
 if(b?.status==='REJECTED'){mark(s,p,'BLOCKED_CONGRESS',news);continue;}if(b?.status==='VETOED'){mark(s,p,'BLOCKED_EXECUTIVE',news);continue;}
 if(s.time.day>=p.dueDay)mark(s,p,'EXPIRED',news);
 }}
function daily(s,news){initialize(s);for(const m of s.governance.measures){if(m.status==='IMPLEMENTING'&&s.time.day>=m.readyDay){m.status='ACTIVE';news(s,'Medida en servicio',definitions[m.policyId].name,'gobierno')}if(m.status==='ACTIVE'&&s.time.day>=m.endDay){m.status='COMPLETED';news(s,'Finalizó una medida',definitions[m.policyId].name,'gobierno')}}review(s,news)}
function run(s,type,a,{transfer,news}){
 if(!['GOVERNMENT_MEASURE','PROMISE_CREATE','PROMISE_LINK','PROMISE_ABANDON'].includes(type))return false;
 const g=initialize(s),p=s.player;
 if(type==='GOVERNMENT_MEASURE'){
  const d=definitions[a.id];check(d,'Medida inexistente');check(s.politics.president.id===p.id&&p.role==='PRESIDENT','Facultad del Presidente electo');check(near(s,['executive']),'Acercate al escritorio presidencial');check(g.measures.filter(m=>['IMPLEMENTING','ACTIVE'].includes(m.status)).length<8,'Ya hay ocho medidas en ejecución');check(!g.measures.some(m=>m.policyId===a.id&&['IMPLEMENTING','ACTIVE'].includes(m.status)),'Esa medida ya está en ejecución');
  transfer(s,'treasury','population',d.budgetCost,'Medida de gobierno: '+d.name);s.economy.balance=Math.round((s.economy.revenue-s.economy.spending)*100)/100;
  g.budget.byArea[d.category]=(g.budget.byArea[d.category]||0)+d.budgetCost;g.budget.totalCommitted+=d.budgetCost;
  g.measures.push({id:++s.seq,policyId:a.id,author:p.id,party:p.party,status:'IMPLEMENTING',cost:d.budgetCost,created:s.time.day,readyDay:s.time.day+d.implementationTime,endDay:s.time.day+d.implementationTime+d.duration});news(s,'Medida contratada',d.name+': ₳ '+d.budgetCost+'; servicio desde el día '+(s.time.day+d.implementationTime)+'.','gobierno');
 }else if(type==='PROMISE_CREATE'){
  check(s.session.phase==='CAMPAIGN','Las promesas se registran durante campaña');const party=s.politics.parties.find(t=>t.id===p.party);check(party?.candidates.president===p.id,'Solo la candidatura presidencial registra promesas');check(near(s,['campaign']),'Acercate al micrófono de campaña');const def=G.ArgentumData.laws[a.key];check(def&&Number.isFinite(a.value)&&a.value*def.factor>=def.min&&a.value*def.factor<=def.max,'Objetivo fuera del marco legal');check(Math.abs(a.value-s.policy[a.key])>.00001,'Prometé un cambio concreto');const cycle=s.politics.constitution.totalCycles;check(!g.promises.some(x=>x.party===p.party&&x.cycle===cycle&&x.key===a.key),'Ya prometiste ese instrumento en esta campaña');check(g.promises.filter(x=>x.party===p.party&&x.cycle===cycle).length<5,'Máximo cinco promesas por campaña');
  g.promises.push({id:++s.seq,author:p.id,party:p.party,key:a.key,value:a.value,baseline:s.policy[a.key],title:def.name+' → '+Math.round(a.value*def.factor)+def.unit,cycle,status:'CAMPAIGN',created:s.time.day,billId:null,history:[{day:s.time.day,status:'CAMPAIGN'}]});news(s,'Compromiso de campaña registrado',party.name+': '+g.promises.at(-1).title,'política');
 }else{
  const promise=g.promises.find(x=>x.id===a.id);check(promise&&promise.author===p.id,'Solo el autor gestiona la promesa');check(['IN_PROGRESS','BLOCKED_CONGRESS','BLOCKED_EXECUTIVE'].includes(promise.status),'La promesa no está en ejecución');check(near(s,['executive']),'Acercate al escritorio presidencial');check(s.politics.president.id===p.id,'Requiere ejercer la Presidencia');
  if(type==='PROMISE_LINK'){const b=s.politics.bills.find(x=>x.id===a.billId);check(b&&b.author===p.id&&b.key===promise.key&&Math.abs(b.value-promise.value)<.00001,'El proyecto debe ser propio y coincidir con el compromiso');check(!promise.billId||promise.status.startsWith('BLOCKED'),'Ya hay un proyecto vinculado');check(!['REJECTED','VETOED'].includes(b.status),'Vinculá un proyecto nuevo o vigente');promise.billId=b.id;mark(s,promise,'IN_PROGRESS',news);promise.history.push({day:s.time.day,status:'BILL_LINKED',billId:b.id});review(s,news);}
  else mark(s,promise,'ABANDONED',news);
 }
 return true;
}
function validate(s){if(!s.governance)return;const g=s.governance;check(g.budget&&Number.isFinite(g.budget.totalCommitted)&&g.budget.totalCommitted>=0&&Object.values(g.budget.byArea).every(x=>Number.isFinite(x)&&x>=0),'Presupuesto inválido');check(g.schema===1&&Array.isArray(g.measures)&&Array.isArray(g.promises),'Gobierno inválido');for(const m of g.measures){const d=definitions[m.policyId];check(d&&m.cost===d.budgetCost&&['IMPLEMENTING','ACTIVE','COMPLETED'].includes(m.status),'Medida inválida');check(Number.isInteger(m.readyDay)&&m.endDay>m.readyDay,'Plazo inválido')}for(const p of g.promises){const d=G.ArgentumData.laws[p.key];check(d&&Number.isFinite(p.value)&&p.value*d.factor>=d.min&&p.value*d.factor<=d.max,'Promesa inválida')}for(const x of Object.values(g.credibility))check(Number.isFinite(x)&&x>=-8&&x<=8,'Credibilidad inválida')}
G.ArgentumGovernance={definitions,initialize,bonus,revise,review,daily,run,validate};if(typeof module!=='undefined')module.exports=G.ArgentumGovernance;
})(globalThis);
