(function(G){
const I=()=>G.ArgentumInteriors;const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));function check(v,m){if(!v)throw Error(m)}const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function initialize(s){s.football={status:'IDLE',remaining:120,score:[0,0],ball:{x:550,y:340,vx:0,vy:0},bots:[],goalPause:0,mode:'practice',lastGoal:null};for(const p of Object.values(s.players)){p.inventory.pistol||=0;p.inventory.knife||=0;p.ammo||={magazine:0,reserve:0};p.equipped||=null;p.cart||={};p.facing||={x:1,y:0};}for(const b of G.ArgentumData.buildings){const room=I().get(b.id);s.world.actors[b.id]||=(room.actors||[]).map(a=>({...a,inside:b.id}));}s.world.actors.outside||=[{id:'pedestrian1',name:'Vecino de la plaza',x:870,y:810,health:100,inside:null},{id:'pedestrian2',name:'Vecina del barrio',x:745,y:820,health:100,inside:null}];}
function actorList(s,inside){return [...Object.values(s.players).filter(p=>p.inside===inside),...(s.world.actors[inside||'outside']||[])];}
function sceneBlocked(s,inside,x,y,r=9){if(inside)return I().blocked(s,inside,x,y,r);return x<20||x>1530||y<20||y>1180||G.ArgentumData.buildings.some(b=>b.kind!=='plaza'&&x>b.x-r&&x<b.x+b.w+r&&y>b.y-r&&y<b.y+b.h+r)}
function warp(s,p,id,position){p.inside=id;p.seated=null;p.cart||={};if(id){const spawn=position||I().get(id).spawn;p.x=spawn.x;p.y=spawn.y}else if(position){p.x=position.x;p.y=position.y}}
function crime(s,attacker,victim,kind='assault'){if(!attacker||attacker.legal!=='FREE')return;let c=s.justice.cases.find(c=>c.suspect===attacker.id&&!['ACQUITTED','RELEASED'].includes(c.status));if(c){c.incidents=(c.incidents||1)+1;return}c={id:++s.seq,crime:kind,suspect:attacker.id,victim:victim?.id||null,reason:kind==='weapons'?'uso de arma contrario a regulación vigente':'agresión registrada por testigos y evidencia de impacto',evidence:.92,status:'INVESTIGATION',nextDay:s.time.day+1,previousRole:attacker.role,weapon:attacker.equipped,incidents:1};s.justice.cases.push(c);s.news.unshift({id:++s.seq,day:s.time.day,title:'Incidente físico registrado',body:attacker.name+': se abre la causa '+c.id+'.',category:'justicia'});attacker.reputation=Math.max(0,attacker.reputation-15);s.goals.combat=true;}
function hurt(s,shooter,victim,damage){if(victim.health<=0)return;victim.health=Math.max(0,victim.health-damage);victim.injured=true;s.world.effects.push({x:victim.x,y:victim.y,inside:victim.inside,time:.4,type:'impact'});crime(s,shooter,victim);if(victim.health===0){victim.incapacitated=true;victim.recoveryDay=s.time.day+2;}}
function footballStart(s,mode){const f=s.football;f.status='PLAYING';f.remaining=120;f.score=[0,0];f.goalPause=0;f.mode=mode;f.ball={x:550,y:340,vx:0,vy:0};f.bots=mode==='match'?[{id:'A1',team:0,x:310,y:240},{id:'A2',team:0,x:340,y:450},{id:'B1',team:1,x:735,y:230},{id:'B2',team:1,x:710,y:440},{id:'B3',team:1,x:980,y:340}]:[];s.player.x=495;s.player.y=340;}
function kick(s,p,power,tx,ty){const f=s.football;check(p.inside==='pitch'&&f.status==='PLAYING'&&f.goalPause<=0,'No hay pelota en juego');check(distance(p,f.ball)<48,'Acercate a la pelota');const dx=tx-p.x,dy=ty-p.y,n=Math.hypot(dx,dy)||1;f.ball.vx=dx/n*power;f.ball.vy=dy/n*power;f.lastTouch=p.id;f.ball.x=p.x+dx/n*23;f.ball.y=p.y+dy/n*23;s.goals.football=true;}
function footballTick(s,dt){const f=s.football;if(f.status!=='PLAYING')return;if(f.goalPause>0){f.goalPause-=dt;if(f.goalPause<=0){f.ball={x:550,y:340,vx:0,vy:0};for(const p of Object.values(s.players).filter(p=>p.inside==='pitch')){p.x=480;p.y=340;}for(const b of f.bots){b.x=b.team?790:320;b.y=190+(Number(b.id.slice(1))||1)*100}}return}f.remaining=Math.max(0,f.remaining-dt);if(f.remaining===0){f.status='FINISHED';s.news.unshift({id:++s.seq,day:s.time.day,title:'Final en El Potrero',body:'Equipo A '+f.score[0]+' — '+f.score[1]+' Equipo B.',category:'ciudad'});return}
const ball=f.ball;for(const bot of f.bots){let target=ball;if(bot.id==='B3')target={x:980,y:clamp(ball.y,260,420)};const dx=target.x-bot.x,dy=target.y-bot.y,n=Math.hypot(dx,dy);if(n>15){bot.x+=dx/n*105*dt;bot.y+=dy/n*105*dt}bot.cooldown=Math.max(0,(bot.cooldown||0)-dt);if(distance(bot,ball)<28&&!bot.cooldown){const tx=bot.team?40:1060,ty=340+Math.sin(s.world.clock+bot.x)*45,dist=Math.hypot(tx-bot.x,ty-bot.y);ball.vx=(tx-bot.x)/dist*420;ball.vy=(ty-bot.y)/dist*420;bot.cooldown=1;f.lastTouch=bot.id}}
for(const p of Object.values(s.players).filter(p=>p.inside==='pitch'&&p.legal==='FREE')){if(distance(p,ball)<24&&Math.hypot(ball.vx,ball.vy)<170){const v=p.facing||{x:1,y:0};ball.x=p.x+v.x*23;ball.y=p.y+v.y*23;ball.vx=v.x*50;ball.vy=v.y*50;f.lastTouch=p.id}}
ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;const damping=Math.exp(-.55*dt);ball.vx*=damping;ball.vy*=damping;if(ball.y<67){ball.y=67;ball.vy=Math.abs(ball.vy)*.78}if(ball.y>613){ball.y=613;ball.vy=-Math.abs(ball.vy)*.78}if(ball.x<58||ball.x>1042){if(ball.y>276&&ball.y<404){const team=ball.x>1042?0:1;f.score[team]++;f.lastGoal={team,scorer:f.lastTouch};f.goalPause=2;ball.vx=ball.vy=0;s.goals.football=true;}else{ball.x=clamp(ball.x,58,1042);ball.vx*=-.78}}}
function tick(s,dt){check(Number.isFinite(dt)&&dt>0&&dt<=.1,'Paso físico inválido');s.world.clock+=dt;for(const p of Object.values(s.players))p.weaponCooldown=Math.max(0,(p.weaponCooldown||0)-dt);for(const shot of s.world.projectiles){const steps=Math.ceil(Math.hypot(shot.vx,shot.vy)*dt/7);for(let i=0;i<steps&&!shot.hit;i++){shot.x+=shot.vx*dt/steps;shot.y+=shot.vy*dt/steps;if(sceneBlocked(s,shot.inside,shot.x,shot.y,2)){shot.hit=true;break}const victim=actorList(s,shot.inside).find(a=>a.id!==shot.owner&&a.health>0&&distance(a,shot)<14);if(victim){hurt(s,s.players[shot.owner],victim,28);shot.hit=true}}shot.life-=dt;}s.world.projectiles=s.world.projectiles.filter(p=>!p.hit&&p.life>0);for(const ef of s.world.effects)ef.time-=dt;s.world.effects=s.world.effects.filter(e=>e.time>0);footballTick(s,dt);}
function run(s,type,a){const p=s.player;switch(type){case 'PHYSICS':tick(s,a.dt);break;
case 'MOVE':{check(!p.seated,'Levantate de la silla con E');check(!p.incapacitated,'Necesitás atención médica');check(Number.isFinite(a.x)&&Number.isFinite(a.y),'Posición inválida');const dist=Math.hypot(a.x-p.x,a.y-p.y);check(dist<=25,'Paso demasiado grande');check(!sceneBlocked(s,p.inside,a.x,a.y),'Hay una pared, puerta o mueble');if(p.legal==='DETAINED')check(p.inside==='police'&&a.x>690,'Permanecé en el sector de detenidos');if(p.legal==='TRIAL')check(p.inside==='court'&&a.x>680&&a.y<360,'Permanecé en el sector del acusado');if(p.legal==='PRISONER'){const cell=s.justice.cells.find(c=>c.occupantPlayerId===p.id);check(cell,'Celda desconocida');const i=Number(cell.cellId.slice(1))-1;check(a.x>50+i*238&&a.x<237+i*238&&a.y>45&&a.y<407,'La celda está bloqueada')}if(dist>0)p.facing={x:(a.x-p.x)/dist,y:(a.y-p.y)/dist};p.x=a.x;p.y=a.y;if(a.run&&p.energy>5)p.energy=Math.max(5,p.energy-dist*.0007);break}
case 'ENTER':{check(p.legal==='FREE','No podés abandonar custodia');check(!p.inside,'Ya estás en un interior');const b=G.ArgentumData.buildings.find(b=>b.id===a.id);check(b&&Math.hypot(p.x-b.x-b.w/2,p.y-b.y-b.h-20)<80,'Acercate a la puerta');p.returnPosition={x:b.x+b.w/2,y:b.y+b.h+25};warp(s,p,b.id);break}
case 'EXIT':{check(p.legal==='FREE','No podés salir durante custodia');const room=I().get(p.inside);check(room&&I().near(p,room.exit,55),'Acercate a la puerta de salida');const b=G.ArgentumData.buildings.find(b=>b.id===p.inside);warp(s,p,null,{x:b.x+b.w/2,y:b.y+b.h+25});break}
case 'DOOR':{const room=I().get(p.inside),door=room?.doors.find(d=>d.id===a.id);check(door&&I().near(p,door),'Acercate a la puerta');if(p.inside==='jail'&&s.justice.cells.find(c=>c.cellId===door.id)?.locked)throw Error('La puerta de la celda está bloqueada');s.world.doors[p.inside]||={};const wasOpen=s.world.doors[p.inside][door.id]??door.open;if(wasOpen)check(!Object.values(s.players).some(a=>a.inside===p.inside&&a.x>door.x-11&&a.x<door.x+door.w+11&&a.y>door.y-11&&a.y<door.y+door.h+11),'Alejate del paso antes de cerrar la puerta');s.world.doors[p.inside][door.id]=!wasOpen;break}
case 'SIT':{if(p.seated){if(p.standingPosition){p.x=p.standingPosition.x;p.y=p.standingPosition.y}p.seated=null;delete p.standingPosition;break}const room=I().get(p.inside),o=room?.objects.find(o=>o.id===a.id);check(o?.kind==='seat'&&I().near(p,o),'Acercate a una silla');check(!Object.values(s.players).some(a=>a.id!==p.id&&a.inside===p.inside&&a.seated===o.id),'Asiento ocupado');p.standingPosition={x:p.x,y:p.y};p.seated=o.id;p.x=o.x+o.w/2;p.y=o.y+o.h/2;p.energy=Math.min(100,p.energy+2);break}
case 'CART_ADD':{check(p.inside==='market','Entrá al supermercado');const shelf=I().get('market').objects.find(o=>o.id===a.id);check(shelf?.kind==='shelf'&&I().near(p,shelf),'Acercate a una góndola');const n=p.cart[shelf.product]||0;check(n<s.world.stock.market[shelf.product],'No hay más stock');p.cart[shelf.product]=n+1;break}
case 'CART_CLEAR':p.cart={};break;
case 'TEST_KIT':{check(p.legal==='FREE','Acción restringida');const o=I().nearest(s);check(o?.kind==='armory','Acercate al armario de equipo');check(!p.testKit,'Ya retiraste tu equipo de prueba');p.inventory.pistol=1;p.inventory.knife=1;p.ammo={magazine:6,reserve:18};p.testKit=true;break}
case 'EQUIP':{check(p.legal==='FREE','No podés equipar en custodia');check(a.id===null||['pistol','knife'].includes(a.id)&&p.inventory[a.id]>0,'No tenés esa arma');p.equipped=a.id;break}
case 'RELOAD':{check(p.equipped==='pistol'&&p.ammo.reserve>0,'No hay munición de reserva');check(!p.weaponCooldown,'Esperá un instante');const n=Math.min(6-p.ammo.magazine,p.ammo.reserve);p.ammo.magazine+=n;p.ammo.reserve-=n;p.weaponCooldown=.7;break}
case 'ATTACK':{check(p.legal==='FREE'&&!p.incapacitated,'No podés atacar en este estado');check(p.equipped,'Equipá un arma');check(!p.weaponCooldown,'Esperá entre ataques');check(Number.isFinite(a.x)&&Number.isFinite(a.y),'Dirección inválida');const dx=a.x-p.x,dy=a.y-p.y,n=Math.hypot(dx,dy)||1;p.facing={x:dx/n,y:dy/n};if(p.equipped==='pistol'){check(p.ammo.magazine>0,'Cargador vacío. Recargá con R.');p.ammo.magazine--;p.weaponCooldown=.3;s.world.projectiles.push({id:++s.seq,owner:p.id,inside:p.inside,x:p.x+dx/n*17,y:p.y+dy/n*17,vx:dx/n*700,vy:dy/n*700,life:1.4});}else{p.weaponCooldown=.5;const v=actorList(s,p.inside).find(v=>v.id!==p.id&&v.health>0&&distance(p,v)<52&&((v.x-p.x)*dx+(v.y-p.y)*dy)/(Math.max(1,distance(p,v))*n)>.45);if(v)hurt(s,p,v,18);s.world.effects.push({type:'swing',x:p.x+dx/n*25,y:p.y+dy/n*25,inside:p.inside,time:.2})}if(s.policy.weapons===2&&p.role!=='POLICE')crime(s,p,null,'weapons');break}
case 'FOOTBALL_START':check(p.inside==='pitch','Entrá a la cancha');footballStart(s,a.mode==='match'?'match':'practice');break;
case 'KICK':kick(s,p,a.pass?280:620,Number.isFinite(a.x)?a.x:p.x+(p.facing?.x||1)*100,Number.isFinite(a.y)?a.y:p.y+(p.facing?.y||0)*100);break;
case 'TALK':{const actor=actorList(s,p.inside).find(x=>x.id===a.id);check(actor&&actor.id!==p.id&&distance(actor,p)<75,'Acercate al personaje');s.world.lastConversation={actor:actor.name,text:actor.injured?'Necesito atención en el hospital.':s.economy.inflation>3?'Los precios me preocupan. Quiero una propuesta concreta.':'Quiero trabajo, servicios y reglas que se cumplan.'};break}
default:return false;}return true;}
function legalDaily(s,verdict){for(const c of s.justice.cases){const p=s.players[c.suspect];if(c.status==='INVESTIGATION'&&s.time.day>=c.nextDay){c.status='CHARGED';c.nextDay=s.time.day+1;if(p){p.legal='DETAINED';p.equipped=null;warp(s,p,'police',{x:840,y:450})}}else if(c.status==='CHARGED'&&s.time.day>=c.nextDay){c.status='TRIAL';c.nextDay=s.time.day+1;if(p){p.legal='TRIAL';warp(s,p,'court',{x:850,y:285})}}else if(c.status==='TRIAL'&&s.time.day>=c.nextDay){const judge=s.players[s.politics.judge.id];if(!judge||judge.isBot||judge.id===c.suspect)verdict(s,c,c.evidence>=.6?'CONVICT':'ACQUIT');}else if(c.status==='CONVICTED'&&s.time.day>=c.releaseDay){c.status='RELEASED';Object.assign(s.justice.cells.find(x=>x.cellId===c.cellId),{doorState:'OPEN',locked:false,occupantPlayerId:null});if(p){p.role=s.politics.president.id===p.id?'PRESIDENT':s.politics.judge.id===p.id?'JUDGE':'CIVIL';p.legal='FREE';warp(s,p,'jail',{x:500,y:660})}s.goals.justice=true;}}
for(const p of Object.values(s.players)){if(p.legal!=='FREE'){p.hunger=Math.max(p.hunger,55);p.hydration=Math.max(p.hydration,60)}if(p.incapacitated&&s.time.day>=p.recoveryDay){p.incapacitated=false;p.health=55;if(p.legal==='FREE')warp(s,p,'hospital',{x:500,y:650})}}for(const actors of Object.values(s.world.actors))for(const a of actors)if(a.incapacitated&&s.time.day>=a.recoveryDay){a.health=70;a.incapacitated=false;}}
G.ArgentumPhysical={initialize,run,warp,legalDaily,actorList,sceneBlocked};if(typeof module!=='undefined')module.exports=G.ArgentumPhysical;
})(globalThis);
